spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${MYSQL_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${DB_HOST}
      port: ${REDIS_PORT}

  mail:
    host: smtp.qq.com
    username: ${QQ_EMAIL}
    password: ${QQ_EMAIL_CODE}
    default-encoding: UTF-8

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

mybatis:
  mapper-locations: com.nqff.drms.mapper/*
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

mybatis-plus:
  global-config:
    db-config:
      id-type: auto